export const  GET_MOVIES = 'GET_MOVIES';
export const  GET_MOVIES_OK = 'GET_MOVIES_OK';
export const  GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';
export const  GET_MOVIESPAGE_OK = 'GET_MOVIESPAGE_OK';
export const  GET_MOVIESPAGE_ERROR = 'GET_MOVIESPAGE_ERROR';

export const  GET_MOVIE_ESPECIFIC = 'GET_MOVIE_ESPECIFIC';
export const  GET_MOVIES_ESPECIFICOK = 'GET_MOVIES_ESPECIFICOK';
export const  GET_MOVIES_ESPECIFICERROR = 'GET_MOVIES_ESPECIFICERROR';
export const  RETURN_BACK = 'RETURN_BACK'

export const GET_TVSEASONS = 'GET_TVSEASONS'
export const GET_TVSEASONS_OK = 'GET_TVSEASONS_OK'
export const GET_TVSEASONS_ERROR = 'GET_TVSEASONS_ERROR'